spring:
  application:
    name: portifolio
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

portfolio:
  external-members:
    base-url: http://localhost:8080/api/external
  security:
    username: admin
    password: admin123
